language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.3

before_install: ./travis-ci/before_install.sh
before_script: ./travis-ci/before_script.sh
script: ./travis-ci/script.sh
