language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install: ./travis-ci/osx/before_install.sh
      before_script: ./travis-ci/osx/before_script.sh
      script: ./travis-ci/osx/script.sh
      after_failure: ./travis-ci/osx/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=debian
      - MIKTEX_LINUX_DIST_VERSION=10
      - MIKTEX_LINUX_DIST_CODE_NAME=buster
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=debian
      - MIKTEX_LINUX_DIST_VERSION=9
      - MIKTEX_LINUX_DIST_CODE_NAME=stretch
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=ubuntu
      - MIKTEX_LINUX_DIST_VERSION=18.04
      - MIKTEX_LINUX_DIST_CODE_NAME=bionic
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=ubuntu
      - MIKTEX_LINUX_DIST_VERSION=16.04
      - MIKTEX_LINUX_DIST_CODE_NAME=xenial
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=fedora
      - MIKTEX_LINUX_DIST_VERSION=28
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh
    - os: linux
      services: docker
      env:
      - MIKTEX_LINUX_DIST=opensuse
      - MIKTEX_LINUX_DIST_VERSION=15
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh

notifications:
  email: false
