language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install: ./travis-ci/osx/before_install.sh
      before_script: ./travis-ci/osx/before_script.sh
      script: ./travis-ci/osx/script.sh
      after_failure: ./travis-ci/osx/after_failure.sh
    - os: linux
      services: docker
      script: ./travis-ci/docker/script.sh debian buster
    - os: linux
      services: docker
      script: ./travis-ci/docker/script.sh debian stretch
    - os: linux
      services: docker
      script: ./travis-ci/docker/script.sh ubuntu bionic
    - os: linux
      services: docker
      script: ./travis-ci/docker/script.sh ubuntu xenial
    - os: linux
      services: docker
      script: ./travis-ci/docker/script.sh fedora 28 false

notifications:
  email: false
